# Generated by Django 3.1.7 on 2021-03-11 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0002_auto_20210311_2009'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnionBoard',
            fields=[
                ('shop_url', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=200)),
                ('pro_name', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.CharField(blank=True, max_length=100, null=True)),
                ('delivery_fee', models.CharField(blank=True, max_length=100, null=True)),
                ('date_time', models.DateTimeField(blank=True, null=True)),
                ('img_path', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'union_board',
                'managed': False,
            },
        ),
    ]
