# Generated by Django 3.1.7 on 2021-03-11 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0003_unionboard'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
